export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGOUT_USER = 'LOGIN_USER_FAIL';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const DETAILS_USER_REQUEST = 'DETAILS_USER_REQUEST';
export const DETAILS_USER_SUCCESS = 'DETAILS_USER_SUCCESS';
export const DETAILS_USER_FAIL = 'DETAILS_USER_FAIL';
export const DETAILS_USER_RESET = 'DETAILS_USER_RESET';

export const UPDATE_PROFILE_USER_REQUEST = 'UPDATE_PROFILE_USER_REQUEST';
export const UPDATE_PROFILE_USER_SUCCESS = 'UPDATE_PROFILE_USER_SUCCESS';
export const UPDATE_PROFILE_USER_FAIL = 'UPDATE_PROFILE_USER_FAIL';
export const UPDATE_PROFILE_USER_RESET = 'UPDATE_PROFILE_USER_RESET';

export const LIST_USER_REQUEST = 'LIST_USER_REQUEST';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';
export const LIST_USER_FAIL = 'LIST_USER_FAIL';
export const LIST_USER_RESET = 'LIST_USER_RESET';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET';
